version: "3"

services:
  reverse-proxy:
    image: traefik:v2.6
    ports:
      # The HTTP port
      - "127.0.0.1:80:80"
      # The HTTPS port
      - "127.0.0.1:443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "127.0.0.1:8080:8080"
    volumes:
      # Traefik configuration file
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./conf.d:/etc/traefik/conf.d
      - ./acme:/etc/traefik/acme
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    restart: always
  cert-exporter:
    image: ldez/traefik-certs-dumper:v2.8.1
    entrypoint: |
      traefik-certs-dumper file --version v2 --watch
      --source /data/acme.json --dest /data/exported
    volumes:
      - ./acme:/data

networks:
  traefik:
    # Use this network in other docker-compose projects
    name: traefik_overlay
